package exception;

public class FirstException {

	public static void main(String[] args) {
		System.out.println("programe started...");
		try {
			int i=0;
			int j=i/0;
		
		try{
			int a[]=new int[5];
			a[10]=20;
		}catch(Exception e) {
			e.printStackTrace();
		}
		}catch(Exception e) {
			e.printStackTrace();
		}
		System.out.println("programe ended...");
	}
}
